apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  name: job-exporter
  labels:
    app: kube-state-metrics
spec:
  ports:
  - name: job-exporter
    port: 8080
    protocol: TCP
  selector:
    app: job-exporter